language: python
os: linux
dist: bionic

stages:
  - lint
  - test

jobs:
  fast_finish: true

  include:
    - stage: lint
      python: 3.7
      env: "DJANGO='Django>=2.2,<3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"
      script: make lint

    - stage: test
      python: 3.5
      env: "DJANGO='Django>=2.2,<3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"
      script: make coverage

    - stage: test
      python: 3.6
      env: "DJANGO='Django>=2.2,<3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"
      script: make coverage

    - stage: test
      python: 3.7
      env: "DJANGO='Django>=2.2,<3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"
      script: make coverage

    - stage: test
      python: 3.8
      env: "DJANGO='Django>=2.2,<3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"
      script: make coverage

    - stage: test
      python: 3.6
      env: "DJANGO='Django>=3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"
      script: make coverage

    - stage: test
      python: 3.7
      env: "DJANGO='Django>=3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"
      script: make coverage

    - stage: test
      python: 3.8
      env: "DJANGO='Django>=3' OSCAR='https://github.com/django-oscar/django-oscar/archive/master.tar.gz'"
      script: make coverage

before_install:
    - pip install codecov

install:
    - pip install $OSCAR $DJANGO
    - make install
    - pip freeze

after_success:
  - codecov
